language: "python"
sudo: required
python:
  - "3.5"
notifications:
  email: comses-dev@googlegroups.com
services:
  - docker
env: 
  - DOCKER_COMPOSE_VERSION=1.14.0
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y docker-ce
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo sysctl -w vm.max_map_count=262144
install: 
  - echo "1" | ./build.sh 
  - pip3 install python-coveralls coverage
script:
  - docker-compose run --rm cms /code/deploy/test.sh
  - docker-compose up -d && docker-compose exec js /code/deploy/test.sh
after_success:
  - cd django && mv .coverage{,.123} && coverage combine --append && coveralls && cd -
  - cd frontend && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js