language: "python"
python:
  - "3.6"
sudo: required
notifications:
  email: comses-dev@googlegroups.com
addons:
  apt:
    packages:
      - docker-ce
services:
  - docker
env: 
  - DOCKER_COMPOSE_VERSION=1.25.3
  - DJANGO_SETTINGS_MODULE=core.settings.test
before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod a+rx docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo sysctl -w vm.max_map_count=262144
install: 
  - docker --version
  - echo "1" | ./build.sh 
  - pip3 install coveralls coverage
script:
  - docker-compose run --rm cms /code/deploy/test.sh
after_success:
  - bash django/deploy/run-coveralls
  - bash frontend/deploy/run-coveralls
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin;
      docker push comses/cms:dev;
      docker push comses/cmsjs:dev;
    fi
