language: "python"
python:
  - "3.6"
sudo: required
notifications:
  email: comses-dev@googlegroups.com
services:
  - docker
env: 
  - DOCKER_COMPOSE_VERSION=1.23.1
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y docker-ce
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod a+rx docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo sysctl -w vm.max_map_count=262144
install: 
  - echo "1" | ./build.sh 
  - pip3 install python-coveralls coverage
script:
  - bash deploy/run-tests
  - docker-compose run --rm cms /code/deploy/build_docs.sh
after_success:
  - bash django/deploy/run-coveralls
  - bash frontend/deploy/run-coveralls
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin;
      docker push comses/cms:dev;
      docker push comses/cmsjs:dev;
    fi
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
  local-dir: docs/build/html
