services:
  redis:
    image: redis:6-alpine
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./deploy/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/shared/redis:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - ./deploy/elasticsearch.conf.d/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./deploy/elasticsearch.conf.d/elasticsearch-primary.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - ./docker/shared/pgdata:/var/lib/postgresql/data
      - ./deploy/secrets/db_password:/run/secrets/db_password
    environment:
      # FIXME: replace with init sql script, see https://github.com/docker/docker/issues/13490
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
  js:
    build: frontend
    image: comses/cmsjs
    volumes:
      - /code/node_modules
      - ./docker/shared:/shared
      - ./deploy/conf/config.ini:/secrets/config.ini
  cms:
    build: django
    image: comses/cms:dev
    volumes:
      - ./deploy/conf/config.ini:/secrets/config.ini
      - ./deploy/elasticsearch.conf.d:/etc/elasticsearch
      - ./docker/shared:/shared
    depends_on:
      - db
      - js
      - elasticsearch
      - redis
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      CLEAN_DATABASE: "false"
volumes:
  esdata:
    driver: local
