version: '3'
services:
  elasticsearch:
    image: elasticsearch:5
    volumes:
      - ./deploy/elasticsearch.conf.d/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./docker/esdata:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
  ${DB_HOST}:
    image: comses/postgis:9.5
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    environment:
      # FIXME: replace with init sql script, see https://github.com/docker/docker/issues/13490
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
  js:
    build: frontend
    image: comses/cmsjs_dev:latest
    volumes:
      - ./frontend:/code
      - ./docker/shared/webpack:/shared/webpack
      - /code/node_modules
  cms:
    build: django
    image: comses/cms_dev:latest
    volumes:
      - ./django:/code
      - ./deploy/conf/config.ini:/secrets/config.ini
      - ./deploy/elasticsearch.conf.d:/etc/elasticsearch
      - ./docker/shared/logs:/shared/logs
      - ./docker/shared/library:/shared/library
      - ./docker/shared/repository:/shared/repository
      - ./docker/shared/webpack:/shared/webpack
      - ./docker/shared/static:/shared/static
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings.dev"
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      CLEAN_DATABASE: "false"
    ports:
      - "127.0.0.1:8000:8000"
    links:
      - ${DB_HOST}
      - elasticsearch
      - js
