version: '3'
services:
  elasticsearch:
    image: elasticsearch:5
    volumes:
      - ./deploy/elasticsearch.conf.d/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - esindex:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
  ${DB_HOST}:
    image: postgres:9.5
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      # No need to modify if autofilled by ./build.sh envsubst
      # FIXME: eventually replace with init sql script, see https://github.com/docker/docker/issues/13490
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
  cms:
    build: django
    image: comses/wagtailcms
    volumes:
      - .:/code
      - ./deploy/elasticsearch.conf.d:/etc/elasticsearch
      - logs:/code/logs
      - library:/library
      - repository:/repository
      - ./deploy/conf/config.ini:/secrets/config.ini
      - webpack:/webpack
      - static:/static
    command: /code/deploy/app/prod.sh
    args:
      REQUIREMENTS_FILE: requirements-prod.txt
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "127.0.0.1:8000:8000"
    links:
      - ${DB_HOST}
      - elasticsearch
volumes:
  webpack:
    driver: local
  static:
    driver: local
  repository:
    driver: local
  library:
    driver: local
  esindex:
    driver: local
  data:
    driver: local
  logs:
    driver: local
