version: '3'
services:
  elasticsearch:
    image: elasticsearch:5
    restart: always
    volumes:
      - ./deploy/elasticsearch.conf.d/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./docker/esdata:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
  ${DB_HOST}:
    image: comses/postgis:9.5
    restart: always
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    environment:
      # autofilled by ./build.sh envsubst
      # FIXME: replace with init sql script, see https://github.com/docker/docker/issues/13490
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
  js:
    # TODO: build assets into /shared/webpack directly and terminate
    # FIXME: currently needs a second Django `./manage.py collectstatic` to move generated assets from Django into
    # static directory, seems we should be able to skip that step
    # command: "npm run build"
    build: ./frontend
    image: comses/cmsjs:latest
    volumes:
      - ./frontend:/code
      - ./docker/shared/webpack:/shared/webpack
      - /code/node_modules
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./deploy/nginx/nginx-haproxy.conf:/etc/nginx/nginx.conf
      - ./deploy/nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./docker/shared/logs/nginx:/var/log/nginx
      - ./docker/shared/static:/shared/static
      - sockets:/shared/sockets
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "127.0.0.1:8880:80"
    links:
      - cms
  cms:
    build: 
      context: ./django
      args:
        REQUIREMENTS_FILE: requirements-prod.txt
    image: comses/cms:latest
    restart: always
    volumes:
      - ./deploy/conf/config.ini:/secrets/config.ini
      - ./deploy/elasticsearch.conf.d:/etc/elasticsearch
      - ./django/deploy/prod.sh:/etc/service/django/run
      - ./docker/shared/input:/shared/input
      - ./docker/shared/logs/cms:/shared/logs
      - ./docker/shared/library:/shared/library
      - ./docker/shared/repository:/shared/repository
      - ./docker/shared/webpack:/shared/webpack
      - ./docker/shared/static:/shared/static
      - sockets:/shared/sockets
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings.production"
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "127.0.0.1:9191:9191" # uWSGI stats server
    links:
      - ${DB_HOST}
      - elasticsearch
volumes:
    sockets:
