name: CoMSES Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install coveralls and coverage
      run: |
        python -m pip install --upgrade pip
        pip3 install coveralls coverage
    - name: Run Django tests
      run: echo "1" | ./build.sh && docker-compose run --rm cms /code/deploy/test.sh
    - name: run coveralls
      run:
        bash ./django/deploy/run-coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
